# version: '3.9'

services:

  # vision:
  #     build:
  #       context: ./vision
  #       dockerfile: Dockerfile.dev
  #     container_name: vision_app
  #     working_dir: /app
  #     volumes:
  #       - ./vision:/app
  #       - ./vision/.env:/app/.env
  #       - /app/node_modules  # Для NPM-совместимости
  #     ports:
  #       - "5173:5173"
  #     networks:
  #       - olympic
  #     environment:
  #       - CHOKIDAR_USEPOLLING=true
  #       - WATCHPACK_POLLING=true
  #       - HOST=0.0.0.0
  #       - VITE_API_URL=http://localhost:6611

  backend-db:
    image: postgres:16-alpine
    container_name: backend-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_pass
      POSTGRES_DB: ExtremeCourse
    ports:
      - "5444:5432"
    networks:
      - courses
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      backend-db:
        condition: service_healthy
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./backend/config-yaml/docker.yaml:/app/config.yaml:ro

    networks:
      - courses
    ports:
      - "8989:8080"
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: 
      - courses
    volumes:
      - redis_data:/data
      - ./users.acl:/etc/redis/users.acl:ro
    command: ["redis-server", "--aclfile", "/etc/redis/users.acl"]

networks:
  courses:
    driver: bridge

volumes:
  backend-db-data:
  redis_data:
