export interface ParsedAchievement {
    code: string;
    olympiadName: string;
    resultType: "Победитель" | "Призёр" | "Участник" | "Достижение";
    score: number;
    category: "ВсОШ" | "Минобрнауки" | "Сириус" | "Спец. олимпиады";
}

// Базовые соответствия для всех кодов бэкенда
export const ACHIEVEMENT_CATALOG: Record<string, { name: string; result: "Победитель" | "Призёр" | "Участник"; score: number; cat: ParsedAchievement["category"] }> = {
    // Сириус
    SIRIUS_PARTICIPANT: { name: "Профильная смена в ОЦ «Сириус»", result: "Участник", score: 20, cat: "Сириус" },

    // ВсОШ
    VSOSH_REG_WINNER: { name: "ВсОШ: Региональный этап", result: "Победитель", score: 40, cat: "ВсОШ" },
    VSOSH_REG_PRIZE_WINNER: { name: "ВсОШ: Региональный этап", result: "Призёр", score: 20, cat: "ВсОШ" },
    VSOSH_MUN_WINNER: { name: "ВсОШ: Муниципальный этап", result: "Победитель", score: 20, cat: "ВсОШ" },
    VSOSH_MUN_PRIZE_WINNER: { name: "ВсОШ: Муниципальный этап", result: "Призёр", score: 10, cat: "ВсОШ" },
    MATH_REG_WINNER: { name: "ВсОШ по математике: Региональный этап", result: "Победитель", score: 40, cat: "ВсОШ" },
    MATH_REG_PRIZE_WINNER: { name: "ВсОШ по математике: Региональный этап", result: "Призёр", score: 20, cat: "ВсОШ" },
    MATH_MUN_WINNER: { name: "ВсОШ по математике: Муниципальный этап", result: "Победитель", score: 20, cat: "ВсОШ" },
    MATH_MUN_PRIZE_WINNER: { name: "ВсОШ по математике: Муниципальный этап", result: "Призёр", score: 10, cat: "ВсОШ" },

    // Спец. олимпиады
    EULER_WINNER: { name: "Олимпиада им. Леонарда Эйлера", result: "Победитель", score: 20, cat: "Спец. олимпиады" },
    EULER_PRIZE_WINNER: { name: "Олимпиада им. Леонарда Эйлера", result: "Призёр", score: 10, cat: "Спец. олимпиады" },
    MAXWELL_WINNER: { name: "Олимпиада им. Дж. Кл. Максвелла", result: "Победитель", score: 20, cat: "Спец. олимпиады" },
    MAXWELL_PRIZE_WINNER: { name: "Олимпиада им. Дж. Кл. Максвелла", result: "Призёр", score: 10, cat: "Спец. олимпиады" },

    // Перечневые олимпиады (52 олимпиады)
    FINATLON_WINNER: { name: "«Финатлон для старшеклассников»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    FINATLON_PRIZE_WINNER: { name: "«Финатлон для старшеклассников»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    FORMULA_EDINSTVA_WINNER: { name: "«Формула Единства» / «Третье тысячелетие»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    FORMULA_EDINSTVA_PRIZE_WINNER: { name: "«Формула Единства» / «Третье тысячелетие»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VERNADSKY_WINNER: { name: "Олимпиада им. В.И. Вернадского", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VERNADSKY_PRIZE_WINNER: { name: "Олимпиада им. В.И. Вернадского", result: "Призёр", score: 20, cat: "Минобрнауки" },
    NTO_WINNER: { name: "Национальная технологическая олимпиада (НТО)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    NTO_PRIZE_WINNER: { name: "Национальная технологическая олимпиада (НТО)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    INNAGRIKA_WINNER: { name: "Олимпиада по агрогенетике «Иннагрика»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    INNAGRIKA_PRIZE_WINNER: { name: "Олимпиада по агрогенетике «Иннагрика»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VSOSH_AI_WINNER: { name: "Олимпиада по искусственному интеллекту", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VSOSH_AI_PRIZE_WINNER: { name: "Олимпиада по искусственному интеллекту", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VYSSHAYA_PROBA_WINNER: { name: "ВсОШ «Высшая проба»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VYSSHAYA_PROBA_PRIZE_WINNER: { name: "ВсОШ «Высшая проба»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    MISSIYA_VYPOLNIMA_WINNER: { name: "«Миссия выполнима. Твое призвание — финансист!»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    MISSIYA_VYPOLNIMA_PRIZE_WINNER: { name: "«Миссия выполнима. Твое призвание — финансист!»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SECHENOV_WINNER: { name: "Сеченовская олимпиада школьников", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SECHENOV_PRIZE_WINNER: { name: "Сеченовская олимпиада школьников", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VSESIBIRSKAYA_WINNER: { name: "Всесибирская открытая олимпиада", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VSESIBIRSKAYA_PRIZE_WINNER: { name: "Всесибирская открытая олимпиада", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VUZ_AKADEM_INFORMATIKA_WINNER: { name: "Вузовско-академическая по информатике", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VUZ_AKADEM_INFORMATIKA_PRIZE_WINNER: { name: "Вузовско-академическая по информатике", result: "Призёр", score: 20, cat: "Минобрнауки" },
    GORODSKAYA_FIZIKA_WINNER: { name: "Городская открытая по физике", result: "Победитель", score: 40, cat: "Минобрнауки" },
    GORODSKAYA_FIZIKA_PRIZE_WINNER: { name: "Городская открытая по физике", result: "Призёр", score: 20, cat: "Минобрнауки" },
    INZHENERNAYA_WINNER: { name: "Инженерная олимпиада школьников", result: "Победитель", score: 40, cat: "Минобрнауки" },
    INZHENERNAYA_PRIZE_WINNER: { name: "Инженерная олимпиада школьников", result: "Призёр", score: 20, cat: "Минобрнауки" },
    INTERNET_FIZIKA_WINNER: { name: "Интернет-олимпиада по физике", result: "Победитель", score: 40, cat: "Минобрнауки" },
    INTERNET_FIZIKA_PRIZE_WINNER: { name: "Интернет-олимпиада по физике", result: "Призёр", score: 20, cat: "Минобрнауки" },
    INNOPOLIS_OPEN_WINNER: { name: "Международная олимпиада «Innopolis Open»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    INNOPOLIS_OPEN_PRIZE_WINNER: { name: "Международная олимпиада «Innopolis Open»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    FIN_SAFETY_WINNER: { name: "Международная по финансовой безопасности", result: "Победитель", score: 40, cat: "Минобрнауки" },
    FIN_SAFETY_PRIZE_WINNER: { name: "Международная по финансовой безопасности", result: "Призёр", score: 20, cat: "Минобрнауки" },
    IZUMRUD_WINNER: { name: "Олимпиада УрФУ «Изумруд»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    IZUMRUD_PRIZE_WINNER: { name: "Олимпиада УрФУ «Изумруд»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    BIBN_WINNER: { name: "«Будущие исследователи — будущее науки» (БИБН)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    BIBN_PRIZE_WINNER: { name: "«Будущие исследователи — будущее науки» (БИБН)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VERCHENKO_WINNER: { name: "Олимпиада им. И.Я. Верченко", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VERCHENKO_PRIZE_WINNER: { name: "Олимпиада им. И.Я. Верченко", result: "Призёр", score: 20, cat: "Минобрнауки" },
    VEDOMSTVENNYE_WINNER: { name: "Олимпиада на базе ведомственных организаций", result: "Победитель", score: 40, cat: "Минобрнауки" },
    VEDOMSTVENNYE_PRIZE_WINNER: { name: "Олимпиада на базе ведомственных организаций", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SARKISOV_WINNER: { name: "Химическая олимпиада им. академика П.Д. Саркисова", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SARKISOV_PRIZE_WINNER: { name: "Химическая олимпиада им. академика П.Д. Саркисова", result: "Призёр", score: 20, cat: "Минобрнауки" },
    KFU_PREDMETNYE_WINNER: { name: "Межрегиональные предметные олимпиады КФУ", result: "Победитель", score: 40, cat: "Минобрнауки" },
    KFU_PREDMETNYE_PRIZE_WINNER: { name: "Межрегиональные предметные олимпиады КФУ", result: "Призёр", score: 20, cat: "Минобрнауки" },
    YUNYE_TALANTY_WINNER: { name: "Многопредметная олимпиада «Юные таланты»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    YUNYE_TALANTY_PRIZE_WINNER: { name: "Многопредметная олимпиада «Юные таланты»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    MOSH_WINNER: { name: "Московская олимпиада школьников (МОШ)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    MOSH_PRIZE_WINNER: { name: "Московская олимпиада школьников (МОШ)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    OMMO_WINNER: { name: "Объединенная межвузовская олимпиада (ОММО)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    OMMO_PRIZE_WINNER: { name: "Объединенная межвузовская олимпиада (ОММО)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    KURCHATOV_WINNER: { name: "Олимпиада «Курчатов»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    KURCHATOV_PRIZE_WINNER: { name: "Олимпиада «Курчатов»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    POTOMKI_MENDELEEVA_WINNER: { name: "«Потомки Менделеева»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    POTOMKI_MENDELEEVA_PRIZE_WINNER: { name: "«Потомки Менделеева»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SIBIRIADA_WINNER: { name: "«Сибириада. Шаг в мечту»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SIBIRIADA_PRIZE_WINNER: { name: "«Сибириада. Шаг в мечту»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    GRANIT_NAUKI_WINNER: { name: "Олимпиада школьников «Гранит науки»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    GRANIT_NAUKI_PRIZE_WINNER: { name: "Олимпиада школьников «Гранит науки»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    LOMONOSOV_WINNER: { name: "Олимпиада школьников «Ломоносов»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    LOMONOSOV_PRIZE_WINNER: { name: "Олимпиада школьников «Ломоносов»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    NADEZHDA_ENERGETIKI_WINNER: { name: "Олимпиада «Надежда энергетики»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    NADEZHDA_ENERGETIKI_PRIZE_WINNER: { name: "Олимпиада «Надежда энергетики»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    POKORI_VOROBYOVY_WINNER: { name: "«Покори Воробьевы горы!»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    POKORI_VOROBYOVY_PRIZE_WINNER: { name: "«Покори Воробьевы горы!»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    ROBOFEST_WINNER: { name: "Олимпиада «Робофест»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    ROBOFEST_PRIZE_WINNER: { name: "Олимпиада «Робофест»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    FIZTEKH_WINNER: { name: "Олимпиада школьников «Физтех»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    FIZTEKH_PRIZE_WINNER: { name: "Олимпиада школьников «Физтех»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SHAG_V_BUDUSCHEE_WINNER: { name: "Олимпиада «Шаг в будущее»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SHAG_V_BUDUSCHEE_PRIZE_WINNER: { name: "Олимпиада «Шаг в будущее»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    OSHIP_WINNER: { name: "Олимпиада по программированию (ОШИП)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    OSHIP_PRIZE_WINNER: { name: "Олимпиада по программированию (ОШИП)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    TEHNOKUBOK_WINNER: { name: "Олимпиада «ТехноКубок»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    TEHNOKUBOK_PRIZE_WINNER: { name: "Олимпиада «ТехноКубок»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    RANHIGS_WINNER: { name: "Олимпиада школьников РАНХиГС", result: "Победитель", score: 40, cat: "Минобрнауки" },
    RANHIGS_PRIZE_WINNER: { name: "Олимпиада школьников РАНХиГС", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SPBGU_WINNER: { name: "Олимпиада школьников СПбГУ", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SPBGU_PRIZE_WINNER: { name: "Олимпиада школьников СПбГУ", result: "Призёр", score: 20, cat: "Минобрнауки" },
    YUMSH_WINNER: { name: "Олимпиада ЮМШ", result: "Победитель", score: 40, cat: "Минобрнауки" },
    YUMSH_PRIZE_WINNER: { name: "Олимпиада ЮМШ", result: "Призёр", score: 20, cat: "Минобрнауки" },
    BUDUSCHEE_SIBIRI_WINNER: { name: "Олимпиада СФО «Будущее Сибири»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    BUDUSCHEE_SIBIRI_PRIZE_WINNER: { name: "Олимпиада СФО «Будущее Сибири»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    OTKRYTAYA_ITMO_WINNER: { name: "Открытая олимпиада (ИТМО)", result: "Победитель", score: 40, cat: "Минобрнауки" },
    OTKRYTAYA_ITMO_PRIZE_WINNER: { name: "Открытая олимпиада (ИТМО)", result: "Призёр", score: 20, cat: "Минобрнауки" },
    OTKRYTAYA_PROG_WINNER: { name: "Открытая по программированию", result: "Победитель", score: 40, cat: "Минобрнауки" },
    OTKRYTAYA_PROG_PRIZE_WINNER: { name: "Открытая по программированию", result: "Призёр", score: 20, cat: "Минобрнауки" },
    KOGNITIVNYE_TEH_WINNER: { name: "«Когнитивные технологии»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    KOGNITIVNYE_TEH_PRIZE_WINNER: { name: "«Когнитивные технологии»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    ORMO_WINNER: { name: "Олимпиада ОРМО", result: "Победитель", score: 40, cat: "Минобрнауки" },
    ORMO_PRIZE_WINNER: { name: "Олимпиада ОРМО", result: "Призёр", score: 20, cat: "Минобрнауки" },
    OTKRYTAYA_HIMICH_WINNER: { name: "Открытая химическая олимпиада", result: "Победитель", score: 40, cat: "Минобрнауки" },
    OTKRYTAYA_HIMICH_PRIZE_WINNER: { name: "Открытая химическая олимпиада", result: "Призёр", score: 20, cat: "Минобрнауки" },
    GAZPROM_WINNER: { name: "Отраслевая олимпиада «Газпром»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    GAZPROM_PRIZE_WINNER: { name: "Отраслевая олимпиада «Газпром»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    ROSATOM_WINNER: { name: "Олимпиада «Росатом»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    ROSATOM_PRIZE_WINNER: { name: "Олимпиада «Росатом»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    PIROGOV_WINNER: { name: "Пироговская олимпиада", result: "Победитель", score: 40, cat: "Минобрнауки" },
    PIROGOV_PRIZE_WINNER: { name: "Пироговская олимпиада", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SPB_ASTRON_WINNER: { name: "Санкт-Петербургская астрономическая", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SPB_ASTRON_PRIZE_WINNER: { name: "Санкт-Петербургская астрономическая", result: "Призёр", score: 20, cat: "Минобрнауки" },
    SPB_OLIMPIADA_WINNER: { name: "Санкт-Петербургская олимпиада", result: "Победитель", score: 40, cat: "Минобрнауки" },
    SPB_OLIMPIADA_PRIZE_WINNER: { name: "Санкт-Петербургская олимпиада", result: "Призёр", score: 20, cat: "Минобрнауки" },
    TVOY_PUT_V_NAUKU_WINNER: { name: "«Твой путь в настоящую науку»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    TVOY_PUT_V_NAUKU_PRIZE_WINNER: { name: "«Твой путь в настоящую науку»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    TURNIR_GORODOV_WINNER: { name: "«Турнир городов»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    TURNIR_GORODOV_PRIZE_WINNER: { name: "«Турнир городов»", result: "Призёр", score: 20, cat: "Минобрнауки" },
    TURNIR_LOMONOSOVA_WINNER: { name: "Турнир имени М.В. Ломоносова", result: "Победитель", score: 40, cat: "Минобрнауки" },
    TURNIR_LOMONOSOVA_PRIZE_WINNER: { name: "Турнир имени М.В. Ломоносова", result: "Призёр", score: 20, cat: "Минобрнауки" },
    BELCHONOK_WINNER: { name: "Университетская олимпиада «Бельчонок»", result: "Победитель", score: 40, cat: "Минобрнауки" },
    BELCHONOK_PRIZE_WINNER: { name: "Университетская олимпиада «Бельчонок»", result: "Призёр", score: 20, cat: "Минобрнауки" },
};

export function parseAchievement(code: string): ParsedAchievement {
    const found = ACHIEVEMENT_CATALOG[code];
    if (found) {
        return {
            code,
            olympiadName: found.name,
            resultType: found.result,
            score: found.score,
            category: found.cat,
        };
    }
    // Запасной разбор на случай неизвестных кодов
    const isWinner = code.endsWith("_WINNER");
    const isPrize = code.endsWith("_PRIZE_WINNER");
    return {
        code,
        olympiadName: code.replace(/_(WINNER|PRIZE_WINNER)$/, "").replace(/_/g, " "),
        resultType: isWinner ? "Победитель" : isPrize ? "Призёр" : "Достижение",
        score: isWinner ? 40 : isPrize ? 20 : 0,
        category: "Минобрнауки",
    };
}