env: "local"

DB_INFO:
  scheme: "postgres"
  host: "localhost"
  port: 5432 
  name: "ExtremeCourse"
  user: "postgres"
  pass: "root"
  ssl_model: "disable"

HTTP_SERVER_INFO:
  host: "127.0.0.1" # Или "localhost"
  port: "8181"

JWT_INFO:
  key: "lololololololololololololololololololololololololololololol"
  access_duration: 15
  refresh_duration: 7

MIGRATION_INFO:
  automigrate: true
  driver: "pgx"
  migration_path: "./internal/migrations" # Относительный путь от корня проекта

REDIS_INFO:
  address_path: "localhost:6379"

ZVONOK_INFO: 
  campaign_id: "1104562791"
  public_key: "6e51df92fe070ff50cd301aa39ce38b8"
  base_url: ""

RABBIT_INFO:
  address_path: "amqp://sso-service:sso-password@localhost:5672/"
  queue_name: "olymp_sso"

ADDITIONAL_ADDRESSES:
  react: "http://localhost:5173"

ADDITIONAL_SERVICE_ADDRESSES:
  notification_path: "http://localhost:6611/email/send-code"

CREATION_LINKS_TEMPLATE:
  prefix: "https://vos.schooltech.ru/verifyApplications?access_token="